---
output:
  pdf_document: default
  html_document: default
---

# Setup

```{r setup, include=F}
knitr::opts_chunk$set(
  warning = FALSE,
  message = FALSE,
  echo = TRUE,
  tidy = TRUE,
  fig.align = "center",
  tidy.opts = list(width.cutoff = 60))

# Loading Libraries
library(readxl)
library(tidyverse)
require(reshape2)
library(tseries)
library(astsa)
library(forecast)
library(viridis)
library(RQuantLib)
library(stringr)
library(xts)
library(MASS)
library(scales)
library(mvtnorm)
library(mnormt)
library(rugarch)
library(fGarch)
library(broom)
library(FactoMineR)
library(ggplot2)
library(gtable)
library(grid)
library(gridExtra)
library(YieldCurve)
library(bizdays)
library(Metrics)
library(future.apply)
library(foreach)
library(doParallel)
library(matrixStats)
library(parallel)
library(furrr)
library(writexl)
library(arrow)
library(data.table)
library(gginnards)
library(tibble)
library(magrittr)
library(splines)
library(VGAM)
library(lubridate)
library(corrplot)
library(ggcorrplot)

# Setting storage limit
options(future.globals.maxSize = 10000*1024^2)

# Setting plot themes
custom_viridis <- function(n.breaks) scale_color_viridis_c("Tenor (Years)", n.breaks = n.breaks, guide = guide_colorbar(barwidth = 1, barheight = 15))

custom_theme <- function(size = 1) {
  theme(
    plot.title = element_text(size = 12 * size, face = "bold", hjust = 0.5),
    axis.title = element_text(size = 10 * size),
    axis.text = element_text(size = 10 * size),
    legend.title = element_text(size = 10 * size, face = "bold"),
    legend.text = element_text(size = 10 * size),
    legend.background = element_blank(),
    legend.box.background = element_rect(color = "black", fill = NA),
    plot.margin = margin(10, 10, 10, 10),
    text = element_text(size = 12 * size),
    plot.title.position = 'plot',
    legend.position = 'right',
    panel.border = element_rect(color = "black", fill = NA),
  )
}

# Setting parallel processing
plan(multisession, workers = detectCores() - 3)
```

# Importing Data

```{r}
zero_coupon_yields <- as.matrix(read_parquet("Data/zero_coupon_yields.parquet"))
zero_coupon_yields_extrapolated_3M <- as.matrix(read_parquet("Data/zero_coupon_yields_extrapolated_3M.parquet"))
zero_coupon_yields_extrapolated_3M_replaced <- zero_coupon_yields_extrapolated_3M
zero_coupon_yields_extrapolated_3M_replaced[,which(colnames(zero_coupon_yields_extrapolated_3M_replaced) %in% colnames(zero_coupon_yields))] <- zero_coupon_yields
zero_coupon_dates <- as.Date(read.table("Data/zero_coupon_dates.txt", sep = ",")[[1]])

zero_coupon_dates_phase_1 <- zero_coupon_dates[zero_coupon_dates < as.Date("2020-03-01")]
zero_coupon_dates_phase_2 <- zero_coupon_dates[zero_coupon_dates >= as.Date("2020-03-01") & zero_coupon_dates < as.Date("2023-07-01")]
zero_coupon_dates_phase_3 <- zero_coupon_dates[zero_coupon_dates >= as.Date("2023-07-01")]

zero_coupon_yields_phase_1 <- zero_coupon_yields[zero_coupon_dates %in% zero_coupon_dates_phase_1,]
zero_coupon_yields_phase_2 <- zero_coupon_yields[zero_coupon_dates %in% zero_coupon_dates_phase_2,]
zero_coupon_yields_phase_3 <- zero_coupon_yields[zero_coupon_dates %in% zero_coupon_dates_phase_3,]

zero_coupon_yields_extrapolated_3M_phase_1 <- zero_coupon_yields_extrapolated_3M[zero_coupon_dates %in% zero_coupon_dates_phase_1,]
zero_coupon_yields_extrapolated_3M_phase_2 <- zero_coupon_yields_extrapolated_3M[zero_coupon_dates %in% zero_coupon_dates_phase_2,]
zero_coupon_yields_extrapolated_3M_phase_3 <- zero_coupon_yields_extrapolated_3M[zero_coupon_dates %in% zero_coupon_dates_phase_3,]

zero_coupon_yields_extrapolated_3M_replaced_phase_1 <- zero_coupon_yields_extrapolated_3M_replaced[zero_coupon_dates %in% zero_coupon_dates_phase_1,]
zero_coupon_yields_extrapolated_3M_replaced_phase_2 <- zero_coupon_yields_extrapolated_3M_replaced[zero_coupon_dates %in% zero_coupon_dates_phase_2,]
zero_coupon_yields_extrapolated_3M_replaced_phase_3 <- zero_coupon_yields_extrapolated_3M_replaced[zero_coupon_dates %in% zero_coupon_dates_phase_3,]
```

# Extrapolating Data

```{r}
.factorBeta1 <- function(lambda, maturity) {
  (1 - exp(-lambda * maturity)) / (lambda * maturity)
}

.factorBeta2 <- function(lambda, maturity) {
  beta1 <- (1 - exp(-lambda * maturity)) / (lambda * maturity)
  beta1 - exp(-lambda * maturity)
}

.NS.estimator <- function(rate, maturity, lambda) {
  X <- cbind(1, .factorBeta1(lambda, maturity), .factorBeta2(lambda, maturity))
  betaPar <- setNames(coef(lm.fit(X, rate)), c("beta_0", "beta_1", "beta_2"))
  betaPar[is.na(betaPar)] <- 0  # Ensure no NA values
  list(Par = betaPar, Res = residuals(lm.fit(X, rate)))
}

Nelson.Siegel <- function(rate, maturity) {
  rate <- try.xts(rate, error = as.matrix)
  if (ncol(rate) == 1) rate <- matrix(as.vector(rate), 1, nrow(rate))

  lambdaValues <- maturity
  FinalResults <- matrix(0, nrow(rate), 4)
  colnames(FinalResults) <- c("beta_0", "beta_1", "beta_2", "lambda")

  lambdaOptimized <- vapply(lambdaValues, function(lambda) {
    optimize(.factorBeta2, interval = c(0.001, 1), maturity = lambda, maximum = TRUE)$maximum
  }, numeric(1))

  FinalResults <- future_sapply(1:nrow(rate), function(j) {
    InterResults <- vapply(seq_along(lambdaValues), function(i) {
      lambdaTemp <- lambdaOptimized[i]
      InterEstimation <- .NS.estimator(as.numeric(rate[j, ]), maturity, lambdaTemp)
      BetaCoef <- InterEstimation$Par
      SSR <- ifelse(BetaCoef[1] > 0 & BetaCoef[1] < 20, sum(InterEstimation$Res^2), 1e5)
      c(BetaCoef, lambdaTemp, SSR)
    }, numeric(5))

    BestRow <- which.min(InterResults[5, ])
    InterResults[1:4, BestRow]
  }, future.seed = TRUE)
  
  return(reclass(t(FinalResults), rate))
}

NSrates <- function(Coeff, maturity){
  Curve <- try.xts(matrix(0, nrow(Coeff), length(maturity)), error = as.matrix)
  colnames(Curve) <- make.names(maturity)
  Coeff <- as.matrix(Coeff)
  for (i in 1:nrow(Curve)) {
    Curve[i, ] <- as.numeric(Coeff[i, 1]) * rep(1, length(maturity)) + as.numeric(Coeff[i, 2]) * as.numeric(.factorBeta1(Coeff[i, 4], maturity)) + as.numeric(Coeff[i, 3]) * as.numeric(.factorBeta2(Coeff[i, 4], maturity))
  }
  return(Curve)
}
```

```{r}
extrapolate_fun <- function(rates, frequency = 1/4, type = "Nelson Siegel", show_time = F) {
  if (show_time) start_time <- Sys.time()
  
  tenors <- as.numeric(colnames(rates))
  max_tenors <- tail(tenors, 1)
  
  tenors_extrapolated <- c(1/252, seq(frequency, ceiling(max_tenors), frequency))
  
  if (type == "Nelson Siegel") {
    ns_model <- Nelson.Siegel(rates, tenors)
    rates_extrapolated <- NSrates(ns_model, tenors_extrapolated)
  }
  
  rates_extrapolated <- as.matrix(rates_extrapolated)
  
  colnames(rates_extrapolated) <- as.character(tenors_extrapolated)
  colnames(rates_extrapolated)[1] <- "0"
  rownames(rates_extrapolated) <- 1:nrow(rates_extrapolated)
  
  if (show_time) {
    end_time <- Sys.time()
    print(paste0("Total time taken: ", round(as.numeric(difftime(end_time, start_time, units = "secs")), 3), " seconds"))
  }
  
  return(rates_extrapolated)
}
```

# Plotting Rates

```{r}
plot_rates_fun <- function(rates, plot_title = "Rates", type = NULL, name = NULL, dates = NULL, plot_size = c(10, 5)) {
  rates <- rates * 100
  diff_rates <- apply(rates, 2, diff)
  
  rates_df <- as.data.frame(rates)
  rownames(rates_df) <- NULL
  diff_rates_df <- as.data.frame(diff_rates)
  rownames(diff_rates_df) <- NULL
  
  if (is.null(dates)) {
    rates_df$time <- seq_len(nrow(rates_df))
    diff_rates_df$time <- seq_len(nrow(diff_rates_df))
    
    rates_df_compact <- reshape2::melt(rates_df, id.vars = "time", variable.name = "tenor", value.name = "rate")
    rates_df_compact$tenor <- as.numeric(levels(rates_df_compact$tenor))[rates_df_compact$tenor]
    
    diff_rates_df_compact <- reshape2::melt(diff_rates_df, id.vars = "time", variable.name = "tenor", value.name = "differenced_rate")
    diff_rates_df_compact$tenor <- as.numeric(levels(diff_rates_df_compact$tenor))[diff_rates_df_compact$tenor]
  } else {
    rates_df$time <- dates
    diff_rates_df$time <- head(dates, -1)
    
    rates_df_compact <- reshape2::melt(rates_df, id.vars = "time", variable.name = "tenor", value.name = "rate")
    rates_df_compact$tenor <- as.numeric(levels(rates_df_compact$tenor))[rates_df_compact$tenor]
    
    diff_rates_df_compact <- reshape2::melt(diff_rates_df, id.vars = "time", variable.name = "tenor", value.name = "differenced_rate")
    diff_rates_df_compact$tenor <- as.numeric(levels(diff_rates_df_compact$tenor))[diff_rates_df_compact$tenor]
  }
  
  tenors <- as.numeric(colnames(rates))
  tenor_lim <- c(floor(min(tenors)), ceiling(max(tenors)))
  
  rate_time_plot <- ggplot(rates_df_compact) +
    geom_line(aes(x = time, y = rate, group = tenor, color = tenor), size = .4) +
    # labs(title = plot_title, x = "Time", y = "Rate") +
    labs(x = "Time", y = "Rate") +
    scale_y_continuous(labels = scales::percent_format(scale = 1)) +
    custom_viridis(10) +
    custom_theme()
  
  if (is.null(dates)) {
    rate_time_plot <- rate_time_plot + xlim(0, nrow(rates_df))
  } else {
    rate_time_plot <- rate_time_plot + scale_x_date(date_labels = "%Y-%m", date_breaks = "1 year")
  }
  
  diff_rate_time_plot <- ggplot(diff_rates_df_compact) +
    geom_line(aes(x = time, y = differenced_rate, group = tenor, color = tenor), size = .4) +
    # labs(title = paste0("Differenced ", plot_title), x = "Time", y = "Rate") +
    labs(x = "Time", y = "Rate") +
    scale_y_continuous(labels = scales::percent_format(scale = 1)) +
    custom_viridis(10) +
    custom_theme()
  
  if (is.null(dates)) {
    diff_rate_time_plot <- diff_rate_time_plot + xlim(0, nrow(diff_rates_df))
  } else {
    diff_rate_time_plot <- diff_rate_time_plot + scale_x_date(date_labels = "%Y-%m", date_breaks = "1 year")
  }
  
  print(rate_time_plot)
  print(diff_rate_time_plot)
  
  rate_tenor_plot <- ggplot(rates_df_compact) +
    geom_line(aes(x = tenor, y = rate, group = time, color = time), size = .4) +
    # labs(title = type, x = "Tenor", y = "Rate") +
    labs(x = "Tenor", y = "Rate") +
    scale_y_continuous(labels = scales::percent_format(scale = 1)) +
    xlim(tenor_lim) +
    custom_viridis(15) +
    custom_theme()
  
  diff_rate_tenor_plot <- ggplot(diff_rates_df_compact) +
    geom_line(aes(x = tenor, y = differenced_rate, group = time, color = time), size = .4) +
    # labs(title = paste0("Differenced ", type), x = "Tenor", y = "Rate") +
    labs(x = "Tenor", y = "Rate") +
    scale_y_continuous(labels = scales::percent_format(scale = 1)) +
    xlim(tenor_lim) +
    custom_viridis(15) +
    custom_theme()
  
  print(rate_tenor_plot)
  print(diff_rate_tenor_plot)
  
  if (!is.null(name)) {
    ggsave(paste0(name, "_time_plot.png"), rate_time_plot, "png", paste0("Figs/", type), width = plot_size[1], height = plot_size[2])
    ggsave(paste0(name, "_diff_time_plot.png"), diff_rate_time_plot, "png", paste0("Figs/", type), width = plot_size[1], height = plot_size[2])
    ggsave(paste0(name, "_tenor_plot.png"), rate_tenor_plot, "png", paste0("Figs/", type), width = plot_size[1], height = plot_size[2])
    ggsave(paste0(name, "_diff_tenor_plot.png"), diff_rate_tenor_plot, "png", paste0("Figs/", type), width = plot_size[1], height = plot_size[2])
  }
}
```

```{r fig.align = "center", fig.width = 10, fig.height = 5}
plot_rates_fun(zero_coupon_yields, "Zero Coupon Yields", "Interest Rates", "zero_coupon_yields_dates", zero_coupon_dates)
plot_rates_fun(zero_coupon_yields, "Zero Coupon Yields", "Interest Rates", "zero_coupon_yields_dates_small", zero_coupon_dates, plot_size = c(10, 4))
```

```{r fig.align = "center", fig.width = 10, fig.height = 5}
plot_rates_fun(zero_coupon_yields_phase_1, "Zero Coupon Yields Phase 1", "Interest Rates", "zero_coupon_yields_phase_1_dates", zero_coupon_dates_phase_1)
plot_rates_fun(zero_coupon_yields_phase_2, "Zero Coupon Yields Phase 2", "Interest Rates", "zero_coupon_yields_phase_2_dates", zero_coupon_dates_phase_2)
plot_rates_fun(zero_coupon_yields_phase_3, "Zero Coupon Yields Phase 3", "Interest Rates", "zero_coupon_yields_phase_3_dates", zero_coupon_dates_phase_3)
plot_rates_fun(zero_coupon_yields_phase_3, "Zero Coupon Yields Phase 3", "Interest Rates", "zero_coupon_yields_phase_3_dates_small", zero_coupon_dates_phase_3, plot_size = c(10, 4))
```

# Plotting the yield curve

```{r}
plot_yield_curve_fun <- function(rates, plot_title = "Yield Curve", type = NULL, name = NULL, time = NULL, plot_size = c(10, 5), extrapolate = F, extrapolate_frequency = 1/4) {
  rates <- rates * 100
  if (is.null(time)) {
    yield_curve <- as.numeric(tail(rates, 1))
  } else {
    yield_curve <- as.numeric(rates[time, ])
  }
  tenors <- as.numeric(colnames(rates))
  
  yield_curve_df <- data.frame(tenors = tenors, yield_curve = yield_curve)
  
  if (extrapolate) {
    yield_curve <- t(as.matrix(yield_curve))
    colnames(yield_curve) <- tenors
    yield_curve_extrapolated <- extrapolate_fun(yield_curve, frequency = extrapolate_frequency, type = "Nelson Siegel", show_time = F)
    tenors_extrapolated <- as.numeric(colnames(yield_curve_extrapolated))
    yield_curve_extrapolated_df <- data.frame(tenors = tenors_extrapolated, yield_curve = as.numeric(yield_curve_extrapolated))
    yield_curve_plot <- ggplot(yield_curve_extrapolated_df) +
      geom_line(aes(x = tenors, y = yield_curve), col = "red", size = .75) +
      geom_point(aes(x = tenors, y = yield_curve), col = "red", size = 2) +
      geom_line(data = yield_curve_df, aes(x = tenors, y = yield_curve), size = .75) +
      geom_point(data = yield_curve_df, aes(x = tenors, y = yield_curve), size = 2) +
      # labs(title = plot_title, x = "Tenor", y = "Yield") +
      labs(x = "Tenor", y = "Yield") +
      scale_y_continuous(labels = scales::percent_format(scale = 1)) +
      xlim(0, round(max(tenors_extrapolated), 0)) +
      custom_theme()
  } else {
    yield_curve_plot <- ggplot(yield_curve_df) +
      geom_line(aes(x = tenors, y = yield_curve), size = .75) +
      geom_point(aes(x = tenors, y = yield_curve), size = 2) +
      # labs(title = plot_title, x = "Tenor", y = "Yield") +
      labs(x = "Tenor", y = "Yield") +
      scale_y_continuous(labels = scales::percent_format(scale = 1)) +
      xlim(0, round(max(tenors), 0)) +
      custom_theme()
  }
  
  print(yield_curve_plot)
  
  if (!is.null(name)) {
    ggsave(paste0(name, "_yield_curve.png"), yield_curve_plot, "png", paste0("Figs/", type), width = plot_size[1], height = plot_size[2])
  }
}
```

```{r fig.align = "center", fig.width = 10, fig.height = 5}
plot_yield_curve_fun(zero_coupon_yields, "Current Zero Coupon Yield Curve", "Interest Rates", "current_zero_coupon_yields_w_extrapolated_curve", extrapolate = T, plot_size = c(10, 4))
```

# Running PCA

```{r}
plot_scree_plot_fun <- function(variance_explained, plot_title = "Scree Plot", name = NULL, plot_size = c(10, 5)) {
  proportion_variance_explained <- variance_explained[2,]
  # cumulative_variance_explained <- variance_explained[3,]
  
  proportion_variance_explained_df <- as.data.frame(proportion_variance_explained)
  proportion_variance_explained_df$PC <- seq_along(proportion_variance_explained)
  
  scree_plot <- ggplot(proportion_variance_explained_df, aes(x = PC, y = proportion_variance_explained)) +
    geom_line(color = "red", size = .75) +
    geom_point(color = "red", size = 2) +
    # geom_line(aes(x = PC, y = cumsum(proportion_variance_explained)), color = "red", size = 1) +
    # geom_point(aes(x = PC, y = cumsum(proportion_variance_explained)), color = "red", size = 2) +
    # labs(title = "Scree Plot", x = "Principal Component", y = "Proportion of Variance Explained") +
    labs(x = "Principal Component", y = "Proportion of Variance Explained") +
    scale_y_continuous(labels = scales::percent_format(scale = 100)) +
    # xlim(1, length(proportion_variance_explained)) +
    scale_x_continuous(breaks = seq(1, length(proportion_variance_explained), 1)) +
    custom_theme()
  
  print(scree_plot)
  
  if (!is.null(name)) {
    ggsave(paste0(name, "_scree_plot.png"), scree_plot, "png", "Figs/Scree Plots", width = plot_size[1], height = plot_size[2])
  }
}
```

```{r}
annualized_covariance_matrix_fun <- function(rates, musiela = T) {
  tenors <- as.numeric(colnames(rates))
  n_days_in_year <- 252
  
  dt <- 1 / n_days_in_year
  
  df <- apply(rates, 2, diff)
  
  pfptau <- matrix(NA, nrow = nrow(df), ncol = ncol(df))
  colnames(pfptau) <- colnames(df)
  for (i in 2:(ncol(df) - 1)) {
    slope1 <- (rates[-nrow(rates),i] - rates[-nrow(rates),i - 1]) / (tenors[i] - tenors[i - 1])
    slope2 <- (rates[-nrow(rates),i + 1] - rates[-nrow(rates),i]) / (tenors[i + 1] - tenors[i])
    pfptau[,i] <- (slope1 + slope2) / 2
  }
  pfptau[,1] <- (rates[-nrow(rates),2] - rates[-nrow(rates),1]) / (tenors[2] - tenors[1])
  pfptau[,ncol(pfptau)] <- (rates[-nrow(rates),ncol(rates)] - rates[-nrow(rates),ncol(rates) - 1]) / (tenors[ncol(rates)] - tenors[ncol(rates) - 1])
  
  pfptaudt <- pfptau * dt
  
  if (musiela) {
    df_pf <- df - pfptaudt
  } else {
    df_pf <- df
  }
  
  Sigma <- cov(df_pf) * n_days_in_year
  
  return(Sigma)
}
```

```{r}
Sigma <- annualized_covariance_matrix_fun(zero_coupon_yields_phase_3, musiela = F)
corr <- cov2cor(Sigma)
colnames(corr) <- rownames(corr) <- paste0(colnames(zero_coupon_yields_phase_3), "Y")

test_plot <- ggcorrplot(corr[,rev(seq_len(nrow(corr)))],
           ggtheme = custom_theme(),
           outline.color = "white")

print(test_plot)

ggsave("Figs/Correlation/zero_coupon_yields_phase_3_correlation.png", test_plot, "png", width = 5, height = 5)
```

```{r}
rates <- zero_coupon_yields_phase_3

variance_explained <- function(rates, musiela = T) {
  Sigma <- annualized_covariance_matrix_fun(rates, musiela)
  # test <- Matrix::nearPD(Sigma)
  # Sigma - as.matrix(test$mat)
  
  Eigen <- eigen(Sigma)
  pca_std_all <- sqrt(Eigen$values)
  if (any(is.nan(pca_std_all))) {
    Sigma <- as.matrix(Matrix::nearPD(Sigma)$mat)
    Eigen <- eigen(Sigma)
    pca_std_all <- sqrt(Eigen$values)
  }
  pca_comp_all <- Eigen$vectors
  
  proportion_variance_explained <- (pca_std_all^2)/sum(pca_std_all^2)
  cumulative_variance_explained <- cumsum(pca_std_all^2)/sum(pca_std_all^2)
  
  variance_explained <- rbind(
    pca_std_all,
    proportion_variance_explained,
    cumulative_variance_explained
  )
  colnames(variance_explained) <- paste0("PC", 1:length(proportion_variance_explained))
  rownames(variance_explained) <- c("Standard deviation     ", 
                                     "Proportion of Variance", 
                                     "Cumulative Proportion ")
  
  return(round(variance_explained, 5))
}
```

```{r}
variance_explained(zero_coupon_yields)
```

```{r}
plot_scree_plot_fun(variance_explained(zero_coupon_yields), "Scree Plot Zero Coupon Yields", "zero_coupon_yields")
```


```{r}
variance_explained(zero_coupon_yields_phase_3)
```

```{r}
plot_scree_plot_fun(variance_explained(zero_coupon_yields_phase_3), "Scree Plot Zero Coupon Yields Phase 3", "zero_coupon_yields_phase_3")
```

```{r}
pca_fun <- function(rates, n_components = NULL, musiela = T, pca_tolerance = 0.90) {
  
  tenors <- as.numeric(colnames(rates))
  n_days_in_year <- 252
  
  dt <- 1 / n_days_in_year
  dtau <- diff(tenors)
  dtau <- c(dtau, tail(dtau, 1))
  
  df <- apply(rates, 2, diff)
  
  pfptau <- matrix(NA, nrow = nrow(df), ncol = ncol(df))
  colnames(pfptau) <- colnames(df)
  for (i in 2:(ncol(df) - 1)) {
    slope1 <- (rates[-nrow(rates),i] - rates[-nrow(rates),i - 1]) / (tenors[i] - tenors[i - 1])
    slope2 <- (rates[-nrow(rates),i + 1] - rates[-nrow(rates),i]) / (tenors[i + 1] - tenors[i])
    pfptau[,i] <- (slope1 + slope2) / 2
  }
  pfptau[,1] <- (rates[-nrow(rates),2] - rates[-nrow(rates),1]) / (tenors[2] - tenors[1])
  pfptau[,ncol(pfptau)] <- (rates[-nrow(rates),ncol(rates)] - rates[-nrow(rates),ncol(rates) - 1]) / (tenors[ncol(rates)] - tenors[ncol(rates) - 1])
  
  pfptaudt <- pfptau * dt
  
  if (musiela) {
    df_pf <- df - pfptaudt
  } else {
    df_pf <- df
  }
  
  Sigma <- cov(df_pf) * n_days_in_year
  Eigen <- eigen(Sigma)
  pca_std_all <- sqrt(Eigen$values)
  pca_comp_all <- Eigen$vectors
  
  proportion_variance_explained <- (pca_std_all^2)/sum(pca_std_all^2)
  cumulative_variance_explained <- cumsum(pca_std_all^2)/sum(pca_std_all^2)
  
  if (is.null(n_components)) n_components <- sum(cumulative_variance_explained < pca_tolerance) + 1
  
  pca_std <- pca_std_all[1:n_components]
  pca_comp <- as.matrix(pca_comp_all[,1:n_components])
  
  if (n_components == 1) {
    volatilities <- pca_comp * pca_std
    colnames(pca_comp) <- "y1"
    rownames(pca_comp) <- NULL
  } else {
    volatilities <- pca_comp %*% diag(pca_std)
    colnames(volatilities) <- paste0("y", 1:n_components)
    rownames(volatilities) <- NULL
  }
  
  variance_explained <- rbind(
    pca_std_all,
    proportion_variance_explained,
    cumulative_variance_explained
  )
  colnames(variance_explained) <- paste0("PC", 1:length(proportion_variance_explained))
  
  return(list(n_components = n_components, tenors = tenors, volatilities = volatilities, pca_std = pca_std, pca_comp = pca_comp, variance_explained = variance_explained))
}
```

```{r}
zero_coupon_yields_phase_3_pca_1F <- pca_fun(zero_coupon_yields_phase_3, n_components = 1)
zero_coupon_yields_phase_3_pca_2F <- pca_fun(zero_coupon_yields_phase_3, n_components = 2)
zero_coupon_yields_phase_3_pca_3F <- pca_fun(zero_coupon_yields_phase_3, n_components = 3)

# zero_coupon_yields_phase_3_pca_2F$volatilities
# pca_fun(zero_coupon_yields[zero_coupon_dates >= as.Date("2024-01-01"),], n_components = 2)$volatilities
# pca_fun(zero_coupon_yields[zero_coupon_dates >= as.Date("2022-01-01"),], n_components = 2)$volatilities
```

# Plotting Volatilities

```{r}
plot_hjm_volatilites_fun <- function(rates, plot_title, n_components = NULL, musiela = T, pca_tolerance = 0.99, name = NULL, plot_size = c(10, 5)) {
  tenors <- as.numeric(colnames(rates))
  pca <- pca_fun(rates, n_components, musiela, pca_tolerance)
  if (is.null(n_components)) n_components <- pca$n_components
  
  volatilities <- pca$volatilities
  volatilities_df <- as.data.frame(cbind(x = tenors, volatilities))
  volatilities_df_compact <- reshape2::melt(volatilities_df, id.vars = "x", variable.name = "volatility", value.name = "value")
  
  volatilities_plot <- ggplot(volatilities_df_compact, aes(x = x, y = value, color = volatility)) +
    geom_line(size = .75) +
    geom_point(size = 2) +
    # labs(title = plot_title, x = "Tenor", y = "Volatility") +
    labs(x = "Tenor", y = "Volatility") +
    # custom_viridis(10) +
    custom_theme() +
    xlim(0, round(max(tenors), 0)) +
    # scale_color_manual(name = "Volatility", labels = as.character(1:n_components), values = viridis::viridis(n_components)) +
    scale_color_manual(name = "Volatility", labels = seq_len(n_components), values = hue_pal()(n_components)) +
    theme(legend.position = "none")
  
  
  print(volatilities_plot)
  
  if (!is.null(name)) {
    ggsave(paste0(name, "_volatilities_plot.png"), volatilities_plot, "png", "Figs/Volatilities", width = plot_size[1], height = plot_size[2])
  }
}
```

```{r}
plot_hjm_volatilites_fun(zero_coupon_yields, "HJM Volatilities", n_components = 2, name = "zero_coupon_yields")
plot_hjm_volatilites_fun(zero_coupon_yields, "HJM Volatilities", n_components = 2, name = "zero_coupon_yields_small", plot_size = c(10, 3.9))
```

# Fitting HJM model

```{r}
fit_HJM_fun <- function(rates, procedure, volatility_fit_method, n_components = NULL, musiela = T, pca_tolerance = 0.99, extrapolate_frequency = 1/4, extrapolation_method = "Nelson Siegel") {
  
  if (procedure == "1") {
    extrapolate_volatilites = F
  }
  if (procedure == "2") {
    extrapolate_volatilites = T
  }
  
  tenors <- as.numeric(colnames(rates))
  pca <- pca_fun(rates, n_components, musiela, pca_tolerance)
  
  volatilities_mods <- list()
  if (is.null(n_components)) n_components <- pca$n_components
  if (n_components == 1) {
    volatilities <- pca$volatilities
    
    volatilities_df <- data.frame("x" = tenors, "y1" = volatilities)
    
    if (volatility_fit_method == "linear") volatilities_mods[[1]] <- lm(as.formula(paste0("y1 ~ 1 + x + I(x^2) + I(x^3)")), data = volatilities_df)
    if (volatility_fit_method == "spline") volatilities_mods[[1]] <- lm(as.formula(paste0("y1 ~ splines::ns(x, df = 5, intercept = T)")), data = volatilities_df)
  } else {
    volatilities <- pca$volatilities[,1:n_components]
    
    volatilities_df <- as.data.frame(cbind(x = tenors, volatilities))
    
    for (i in 1:n_components) {
      if (volatility_fit_method == "linear") volatilities_mods[[i]] <- lm(as.formula(paste0("y", i, " ~ 1 + x + I(x^2) + I(x^3)")), data = volatilities_df)
      if (volatility_fit_method == "spline") volatilities_mods[[i]] <- lm(as.formula(paste0("y", i, " ~ splines::ns(x, df = 5, intercept = T)")), data = volatilities_df)
    }
  }
  
  tenors_old <- tenors
  if (extrapolate_volatilites) {
    tenors <- seq(0, ceiling(tail(tenors, 1)), extrapolate_frequency)
    todays_rate <- as.numeric(extrapolate_fun(tail(rates, 1), extrapolate_frequency, type = extrapolation_method))
  } else {
    todays_rate <- as.numeric(tail(rates, 1))
  }
  
  volatilities_fitted <- matrix(NA, nrow = length(tenors), ncol = n_components)
  if (n_components == 1) {
    volatilities_fitted[,1] <- predict(volatilities_mods[[1]], data.frame(x = tenors))
  } else {
    for (i in 1:n_components) {
      volatilities_fitted[,i] <- predict(volatilities_mods[[i]], data.frame(x = tenors))
    }
  }
  colnames(volatilities_fitted) <- paste0("y", 1:n_components)
  
  drift <- numeric(length(tenors))
  for (i in 1:length(tenors)) {
    tau <- tenors[i]
    for (j in 1:n_components) {
      drift[i] <- drift[i] + integrate(function(x) predict(volatilities_mods[[j]], data.frame(x = x)), 0, tau)$value * volatilities_fitted[i,j]
    }
  }
  
  return(list(todays_rate = todays_rate, n_dates = nrow(rates), n_components = n_components, volatility_fit_method = volatility_fit_method, procedure = procedure, tenors = tenors, tenors_old = tenors_old, drift = drift, volatilities = volatilities, volatilities_fitted = volatilities_fitted, volatilities_mods = volatilities_mods))
}
```

```{r}
# zero_coupon_yields_HJM_1F_procedure_1_poly_model <- fit_HJM_fun(zero_coupon_yields, procedure = "1", volatility_fit_method = "linear", n_components = 1)
zero_coupon_yields_HJM_2F_procedure_1_poly_model <- fit_HJM_fun(zero_coupon_yields, procedure = "1", volatility_fit_method = "linear", n_components = 2)
# zero_coupon_yields_HJM_1F_procedure_2_poly_model <- fit_HJM_fun(zero_coupon_yields, procedure = "2", volatility_fit_method = "linear", n_components = 1)
zero_coupon_yields_HJM_2F_procedure_2_poly_model <- fit_HJM_fun(zero_coupon_yields, procedure = "2", volatility_fit_method = "linear", n_components = 2)

# zero_coupon_yields_HJM_1F_procedure_1_spline_model <- fit_HJM_fun(zero_coupon_yields, procedure = "1", volatility_fit_method = "spline", n_components = 1)
zero_coupon_yields_HJM_2F_procedure_1_spline_model <- fit_HJM_fun(zero_coupon_yields, procedure = "1", volatility_fit_method = "spline", n_components = 2)
# zero_coupon_yields_HJM_1F_procedure_2_spline_model <- fit_HJM_fun(zero_coupon_yields, procedure = "2", volatility_fit_method = "spline", n_components = 1)
zero_coupon_yields_HJM_2F_procedure_2_spline_model <- fit_HJM_fun(zero_coupon_yields, procedure = "2", volatility_fit_method = "spline", n_components = 2)

zero_coupon_yields_phase_3_HJM_2F_procedure_1_poly_model <- fit_HJM_fun(zero_coupon_yields_phase_3, procedure = "1", volatility_fit_method = "linear", n_components = 2)
zero_coupon_yields_phase_3_HJM_2F_procedure_1_spline_model <- fit_HJM_fun(zero_coupon_yields_phase_3, procedure = "1", volatility_fit_method = "spline", n_components = 2)
zero_coupon_yields_phase_3_HJM_2F_procedure_2_poly_model <- fit_HJM_fun(zero_coupon_yields_phase_3, procedure = "2", volatility_fit_method = "linear", n_components = 2)
zero_coupon_yields_phase_3_HJM_2F_procedure_2_spline_model <- fit_HJM_fun(zero_coupon_yields_phase_3, procedure = "2", volatility_fit_method = "spline", n_components = 2)
```

```{r}
calculate_HJM_fitted_fun <- function(fitted_model, rates) {
  tenors <- as.numeric(colnames(rates))
  drift <- fitted_model$drift
  n_days_in_year <- 252
  dt <- 1/n_days_in_year
  
  fitted_values <- rates
  for (i in 2:nrow(fitted_values)) {
    prev_f <- as.numeric(rates[i - 1,])
    prev_pfptau <- numeric(length(prev_f))
    for (j in 2:(length(prev_f) - 1)) {
      slope1 <- (prev_f[j] - prev_f[j - 1]) / (tenors[j] - tenors[j - 1])
      slope2 <- (prev_f[j + 1] - prev_f[j]) / (tenors[j + 1] - tenors[j])
      prev_pfptau[j] <- (slope1 + slope2) / 2
    }
    prev_pfptau[1] <- (prev_f[2] - prev_f[1]) / (tenors[2] - tenors[1])
    prev_pfptau[length(prev_pfptau)] <- (prev_f[length(prev_f)] - prev_f[length(prev_f) - 1]) / (tenors[length(prev_f)] - tenors[length(prev_f) - 1])
    
    prev_pfptaudt <- prev_pfptau * dt
    
    fitted_values[i,] <- as.numeric(rates[i - 1,]) + drift * dt + prev_pfptaudt
  }
  
  return(fitted_values)
}

calculate_HJM_residuals_fun <- function(fitted_model, rates) {
  residuals <- rates - calculate_HJM_fitted_fun(fitted_model, rates)
  
  return(residuals)
}

calculate_fitted_vs_analytical_variances_fun <- function(fitted_model, rates) {
  tenors <- as.numeric(colnames(rates))
  n_days_in_year <- 252
  
  fitted_variances <- as.numeric(apply(calculate_HJM_residuals_fun(fitted_model, rates), 2, var))
  analytical_variances <- as.numeric(apply(fitted_model$volatilities_fitted^2 * 1/n_days_in_year, 1, sum))
  # analytical_variances <- as.numeric(apply(fitted_model$volatilities_fitted * sqrt(1/n_days_in_year), 1, sum))^2
  
  variances <- rbind(fitted_variances, analytical_variances)
  colnames(variances) <- tenors
  
  return(variances)
}
```

```{r}
# calculate_fitted_vs_analytical_variances_fun(zero_coupon_yields_HJM_1F_procedure_1_poly_model, zero_coupon_yields)
# calculate_fitted_vs_analytical_variances_fun(zero_coupon_yields_HJM_2F_procedure_1_poly_model, zero_coupon_yields)
```

```{r}
# calculate_fitted_vs_analytical_variances_fun(zero_coupon_yields_HJM_1F_procedure_1_spline_model, zero_coupon_yields)
# calculate_fitted_vs_analytical_variances_fun(zero_coupon_yields_HJM_2F_procedure_1_spline_model, zero_coupon_yields)
```

```{r}
# calculate_fitted_vs_analytical_variances_fun(zero_coupon_yields_phase_3_HJM_2F_procedure_1_poly_model, zero_coupon_yields_phase_3)
```

```{r}
# calculate_fitted_vs_analytical_variances_fun(zero_coupon_yields_phase_3_HJM_2F_procedure_1_spline_model, zero_coupon_yields_phase_3)
```

```{r fig.align = "center", fig.width = 10, fig.height = 30}
plot_fitted_vs_residual_qq_plot_fun <- function(fitted_model, rates, name = NULL, show = T, ncol = 4, plot_size = c(12, 9)) {
  tenors <- as.numeric(colnames(rates))
  fitted_values <- calculate_HJM_fitted_fun(fitted_model, rates)
  residuals <- calculate_HJM_residuals_fun(fitted_model, rates)
  variances <- calculate_fitted_vs_analytical_variances_fun(fitted_model, rates)
  
  values <- data.frame(tenors = tenors, fitted = as.vector(fitted_values), residuals = as.vector(residuals))
  
  fitted_vs_residual_plot <- ggplot(values, aes(x = fitted, y = residuals)) +
    geom_point() +
    facet_wrap(~ tenors, ncol = 4) +
    # geom_smooth(method = "lm", se = FALSE, color = "red") +
    geom_abline(slope = 0, intercept = 0, color = "red", size = 1.25) +
    # labs(title = "Fitted vs Residuals", x = "Fitted Values", y = "Residuals") +
    labs(x = "Fitted Values", y = "Residuals") +
    custom_viridis(10) +
    custom_theme(2) +
    theme(axis.text.x = element_text(angle = 45, vjust = 0.5))
  
  qq_plot <- ggplot(values, aes(sample = residuals)) +
    geom_qq() +
    geom_qq_line(color = "red", size = 1.25) +
    facet_wrap(~ tenors, ncol = ncol) +
    # labs(title = "QQ Plot of Residuals", x = "Theoretical Quantiles", y = "Sample Quantiles") +
    labs(x = "Theoretical Quantiles", y = "Sample Quantiles") +
    custom_viridis(10) +
    custom_theme(2)
  
  values_compact <- reshape2::melt(values[,-2], id.vars = "tenors", variable.name = "type", value.name = "value")
  
  set.seed(1)
  theoretical_data <- data.frame(theoretical = as.numeric(mvrnorm(1e6, mu = numeric(length(variances[2,])), Sigma = diag(variances[2,]))), tenors = tenors)
  theoretical_data_compact <- reshape2::melt(theoretical_data, id.vars = "tenors", variable.name = "type", value.name = "value")
  
  values_2 <- rbind(values_compact, theoretical_data_compact)
  
  density_plot <- ggplot(values_2, aes(x = value)) +
    # geom_histogram(aes(y = ..density.., color = type), bins = 100) +
    geom_density(aes(color = type), linewidth = 1.25) +
    # geom_density(aes(x = norm), color = "red", linewidth = 1) +
    facet_wrap(~ tenors, ncol = ncol) +
    # labs(title = "Density Plot of Residuals", x = "Residuals", y = "Density") +
    labs(x = "Residuals", y = "Density") +
    # custom_viridis(10) +
    custom_theme(2) +
    theme(legend.position = "none", axis.text.x = element_text(angle = 45, vjust = 0.5))
  
  
  if (show) {
    print(fitted_vs_residual_plot)
    print(qq_plot)
    print(density_plot)
  }
  
  if (!is.null(name)) {
    ggsave(paste0(name, "_fitted_vs_residual_plot.png"), fitted_vs_residual_plot, "png", "Figs/Model Checking", width = plot_size[1], height = plot_size[2])
    ggsave(paste0(name, "_qq_plot.png"), qq_plot, "png", "Figs/Model Checking", width = plot_size[1], height = plot_size[2])
    ggsave(paste0(name, "_density_plot.png"), density_plot, "png", "Figs/Model Checking", width = plot_size[1], height = plot_size[2])
  }
}
```

```{r}
plot_fitted_vs_residual_qq_plot_fun(zero_coupon_yields_phase_3_HJM_2F_procedure_1_poly_model, zero_coupon_yields_phase_3, name = "zero_coupon_yields_phase_3_HJM_2F_procedure_1_poly_model", show = T, plot_size = c(12, 7.5))
plot_fitted_vs_residual_qq_plot_fun(zero_coupon_yields_phase_3_HJM_2F_procedure_1_spline_model, zero_coupon_yields_phase_3, name = "zero_coupon_yields_phase_3_HJM_2F_procedure_1_spline_model", show = T, plot_size = c(12, 7.5))
```

```{r}
plot_fitted_vs_residual_qq_plot_fun(zero_coupon_yields_phase_3_HJM_2F_procedure_2_poly_model, zero_coupon_yields_extrapolated_3M_phase_3, name = "zero_coupon_yields_phase_3_HJM_2F_procedure_2_poly_model", show = F, plot_size = c(12, 30))
plot_fitted_vs_residual_qq_plot_fun(zero_coupon_yields_phase_3_HJM_2F_procedure_2_spline_model, zero_coupon_yields_extrapolated_3M_phase_3, name = "zero_coupon_yields_phase_3_HJM_2F_procedure_2_spline_model", show = F, plot_size = c(12, 30))
```

# Plotting HJM Model

```{r}
plot_all_hjm_drifts_fun <- function(fitted_models, plot_title = "blank", name = NULL, plot_size = c(10, 5)) {
  drifts <- rev(do.call(c, lapply(fitted_models, function(x) x$drift)))
  tenors <- rev(do.call(c, lapply(fitted_models, function(x) x$tenors)))
  volatility_fit_methods <- rev(sapply(fitted_models, function(x) x$volatility_fit_method))
  procedures <- rev(sapply(fitted_models, function(x) x$procedure))
  methods <- paste0("P: ", rep(procedures, rev(sapply(fitted_models, function(x) length(x$tenors)))), ", \nV: ", rep(volatility_fit_methods, rev(sapply(fitted_models, function(x) length(x$tenors)))), "\n")
  plot_order <- rev(rep(rev(seq_along(fitted_models)), sapply(fitted_models, function(x) length(x$tenors))))
  
  drifts_df <- as.data.frame(cbind(x = tenors, drift = drifts))
  drifts_df$plot_order <- as.factor(plot_order)
  
  drifts_plot <- ggplot(drifts_df) +
    geom_line(aes(x = x, y = drift, color = plot_order, linewidth = plot_order)) +
    # labs(title = plot_title, x = "Tenor", y = "Value") +
    labs(x = "Tenor", y = "Value") +
    custom_theme() +
    scale_linewidth_manual(values = seq(length(fitted_models), by = -1, length.out = length(fitted_models)), guide = "none") +
    scale_color_viridis_d(name = "Model:", labels = unique(methods), guide = guide_legend(reverse = TRUE)) +
    theme(legend.position = "none")
    # scale_linetype_manual(name = "Model:", labels = unique(methods), values = rev(seq_along(fitted_models)), guide = guide_legend(reverse = TRUE))
  
  print(drifts_plot)
  
  if (!is.null(name)) {
    ggsave(paste0(name, "_drifts_plot.png"), drifts_plot, "png", "Figs/Drifts", width = plot_size[1], height = plot_size[2])
  }
}

fitted_2F_phase_3_models <- list(zero_coupon_yields_phase_3_HJM_2F_procedure_1_poly_model,
                                 zero_coupon_yields_phase_3_HJM_2F_procedure_1_spline_model,
                                 zero_coupon_yields_phase_3_HJM_2F_procedure_2_poly_model,
                                 zero_coupon_yields_phase_3_HJM_2F_procedure_2_spline_model)

plot_all_hjm_drifts_fun(fitted_2F_phase_3_models, "Zero Coupon Yield Phase 3 Fitted Drifts 2 Factors", name = "zero_coupon_yields_phase_3_HJM_2F")
plot_all_hjm_drifts_fun(fitted_2F_phase_3_models, "Zero Coupon Yield Phase 3 Fitted Drifts 2 Factors", name = "zero_coupon_yields_phase_3_HJM_2F_small", plot_size = c(10, 3.9))
```

```{r}
plot_all_hjm_fitted_volatilities_fun <- function(fitted_models, plot_title = "blank", name = NULL, plot_size = c(10, 5)) {
  fitted_volatilities <- do.call(rbind, lapply(fitted_models, function(x) x$volatilities_fitted))
  fitted_volatilities <- fitted_volatilities[nrow(fitted_volatilities):1,]
  rownames(fitted_volatilities) <- NULL
  tenors <- rev(do.call(c, lapply(fitted_models, function(x) x$tenors)))
  volatility_fit_methods <- rev(sapply(fitted_models, function(x) x$volatility_fit_method))
  procedures <- rev(sapply(fitted_models, function(x) x$procedure))
  methods <- paste0("P: ", rep(procedures, rev(sapply(fitted_models, function(x) length(x$tenors)))), ", \nV: ", rep(volatility_fit_methods, rev(sapply(fitted_models, function(x) length(x$tenors)))), "\n")
  plot_order <- rev(rep(rev(seq_along(fitted_models)), sapply(fitted_models, function(x) length(x$tenors))))
  n_components <- ncol(fitted_volatilities)
  
  fitted_volatilities_df <- as.data.frame(cbind(x = tenors, fitted_volatilities))
  fitted_volatilities_df$plot_order <- as.factor(plot_order)
  
  fitted_volatilities_df_compact <- reshape2::melt(fitted_volatilities_df, id.vars = c("x", "plot_order"), variable.name = "volatility")
  
  fitted_volatilities_plot <- ggplot(fitted_volatilities_df_compact) +
    geom_line(aes(x = x, y = value, color = plot_order, linetype = volatility, linewidth = plot_order)) +
    # labs(title = plot_title, x = "Tenor", y = "Value") +
    labs(x = "Tenor", y = "Value") +
    custom_theme() +
    scale_linewidth_manual(values = seq(length(fitted_models), by = -1, length.out = length(fitted_models)), guide = "none") +
    scale_color_viridis_d(name = "Model:", labels = unique(methods), guide = guide_legend(reverse = TRUE)) +
    theme(legend.position = "none")
  
  print(fitted_volatilities_plot)
  
  if (!is.null(name)) {
    ggsave(paste0(name, "_fitted_volatilities_plot.png"), fitted_volatilities_plot, "png", "Figs/Fitted Volatilities", width = plot_size[1], height = plot_size[2])
  }
}

plot_all_hjm_fitted_volatilities_fun(fitted_2F_phase_3_models, "Zero Coupon Yield Phase 3 Fitted Volatilities 2 Factors", name = "zero_coupon_yields_phase_3_HJM_2F")
plot_all_hjm_fitted_volatilities_fun(fitted_2F_phase_3_models, "Zero Coupon Yield Phase 3 Fitted Volatilities 2 Factors", name = "zero_coupon_yields_phase_3_HJM_2F_small", plot_size = c(10, 3.9))
```

# Simulating HJM Model

```{r}
simulate_n_hjm_fun <- function(fitted_model, n, only_mean = F) {
  todays_rate <- fitted_model$todays_rate
  n_days <- fitted_model$n_dates
  tenors <- fitted_model$tenors
  drift <- fitted_model$drift
  volatilities_fitted <- fitted_model$volatilities_fitted
  n_comp <- fitted_model$n_components

  rates_simulated <- matrix(NA, nrow = n + 1, ncol = length(tenors))
  colnames(rates_simulated) <- as.character(tenors)
  time <- 0:n + n_days
  rates_simulated[1,] <- todays_rate
  
  epsilons <- matrix(rnorm(n * n_comp), nrow = n, ncol = n_comp)
  if (only_mean) {
    epsilons <- matrix(rep(0, n * n_comp), nrow = n, ncol = n_comp)
  }
  
  n_days_in_year <- 252
  prev_f <- rates_simulated[1,]
  dt <- 1/n_days_in_year
  for (i in 1:n) {
    prev_pfptau <- numeric(length(prev_f))
    for (j in 2:(length(prev_f) - 1)) {
      slope1 <- (prev_f[j] - prev_f[j - 1]) / (tenors[j] - tenors[j - 1])
      slope2 <- (prev_f[j + 1] - prev_f[j]) / (tenors[j + 1] - tenors[j])
      prev_pfptau[j] <- (slope1 + slope2) / 2
    }
    prev_pfptau[1] <- (prev_f[2] - prev_f[1]) / (tenors[2] - tenors[1])
    prev_pfptau[length(prev_pfptau)] <- (prev_f[length(prev_f)] - prev_f[length(prev_f) - 1]) / (tenors[length(prev_f)] - tenors[length(prev_f) - 1])
    
    prev_pfptaudt <- prev_pfptau * dt
    
    if (n_comp == 1) {
      next_dF_pF <- drift * dt + as.vector(volatilities_fitted * as.numeric(epsilons[i,])) * sqrt(dt)
    } else {
      next_dF_pF <- drift * dt + as.vector(volatilities_fitted %*% as.numeric(epsilons[i,])) * sqrt(dt)
    }
    
    next_f <- prev_f + next_dF_pF + prev_pfptaudt
    rates_simulated[i + 1,] <- next_f
    
    prev_f <- next_f
  }

  rates_simulated <- cbind(time, rates_simulated)

  return(rates_simulated)
}

simulate_n_m_hjm_fun <- function(fitted_model, n, m, extrapolate = F, frequency = 1/4, only_mean = F, show_time = F) {
  if (show_time) start_time <- Sys.time()
  
  n <- round(n)
  tenors <- fitted_model$tenors

  if (extrapolate) tenors <- c(0, seq(frequency, ceiling(tail(tenors, 1)), frequency))
  
  if (only_mean) m <- 1
  results <- future_lapply(1:m, function(i) simulate_n_hjm_fun(fitted_model, n, only_mean), future.seed = T)
  
  rates_simulated <- do.call(rbind, results)
  rates_simulated <- cbind(realization = rep(1:m, each = n + 1), rates_simulated)
  
  
  
  if (extrapolate) {
    rates_simulated_extrapolated <- extrapolate_fun(rates_simulated[,-c(1,2)], frequency)
    rates_simulated_extrapolated <- cbind(rates_simulated[,c(1,2)], rates_simulated_extrapolated)
    rates_simulated <- rates_simulated_extrapolated
  }

  if (show_time) end_time <- Sys.time()
  if (show_time) print(paste0("Total time taken: ", round(as.numeric(difftime(end_time, start_time, units = "secs")), 3), " seconds"))

  return(rates_simulated)
}
```

```{r}
# Do not run this chunk. It takes over an hour.

# set.seed(1)
# zero_coupon_yields_phase_3_HJM_2F_procedure_1_poly_model_simulated_10Y_10000_realizations_seed.1 <- simulate_n_m_hjm_fun(zero_coupon_yields_phase_3_HJM_2F_procedure_1_poly_model, n = 252 * 10, m = 10000, extrapolate = T, show_time = T)
# write_parquet(as.data.frame(zero_coupon_yields_phase_3_HJM_2F_procedure_1_poly_model_simulated_10Y_10000_realizations_seed.1), "Simulated Data/zero_coupon_yields_phase_3_HJM_2F_procedure_1_poly_model_simulated_10Y_10000_realizations_seed.1")
# set.seed(1)
# zero_coupon_yields_phase_3_HJM_2F_procedure_1_spline_model_simulated_10Y_10000_realizations_seed.1 <- simulate_n_m_hjm_fun(zero_coupon_yields_phase_3_HJM_2F_procedure_1_spline_model, n = 252 * 10, m = 10000, extrapolate = T, show_time = T)
# write_parquet(as.data.frame(zero_coupon_yields_phase_3_HJM_2F_procedure_1_spline_model_simulated_10Y_10000_realizations_seed.1), "Simulated Data/zero_coupon_yields_phase_3_HJM_2F_procedure_1_spline_model_simulated_10Y_10000_realizations_seed.1")
```


```{r}
# set.seed(1)
# zero_coupon_yields_phase_3_HJM_2F_procedure_2_poly_model_simulated_10Y_10000_realizations_seed.1 <- simulate_n_m_hjm_fun(zero_coupon_yields_phase_3_HJM_2F_procedure_2_poly_model, n = 252 * 10, m = 10000, show_time = T)
# write_parquet(as.data.frame(zero_coupon_yields_phase_3_HJM_2F_procedure_2_poly_model_simulated_10Y_10000_realizations_seed.1), "Simulated Data/zero_coupon_yields_phase_3_HJM_2F_procedure_2_poly_model_simulated_10Y_10000_realizations_seed.1")
# set.seed(1)
# zero_coupon_yields_phase_3_HJM_2F_procedure_2_spline_model_simulated_10Y_10000_realizations_seed.1 <- simulate_n_m_hjm_fun(zero_coupon_yields_phase_3_HJM_2F_procedure_2_spline_model, n = 252 * 10, m = 10000, show_time = T)
# write_parquet(as.data.frame(zero_coupon_yields_phase_3_HJM_2F_procedure_2_spline_model_simulated_10Y_10000_realizations_seed.1), "Simulated Data/zero_coupon_yields_phase_3_HJM_2F_procedure_2_spline_model_simulated_10Y_10000_realizations_seed.1")
```


```{r}
# zero_coupon_yields_phase_3_HJM_2F_poly_model_simulated_10Y_mean <- simulate_n_m_hjm_fun(zero_coupon_yields_phase_3_HJM_2F_procedure_1_poly_model, n = 252 * 10, m = 1, only_mean = T, show_time = T)
# write_parquet(as.data.frame(zero_coupon_yields_phase_3_HJM_2F_poly_model_simulated_10Y_mean), "Simulated Data/zero_coupon_yields_phase_3_HJM_2F_poly_model_simulated_10Y_mean")
# 
# zero_coupon_yields_phase_3_HJM_2F_procedure_1_poly_model_simulated_10Y_mean <- simulate_n_m_hjm_fun(zero_coupon_yields_phase_3_HJM_2F_procedure_1_poly_model, n = 252 * 10, m = 1, extrapolate = T, only_mean = T, show_time = T)
# write_parquet(as.data.frame(zero_coupon_yields_phase_3_HJM_2F_procedure_1_poly_model_simulated_10Y_mean), "Simulated Data/zero_coupon_yields_phase_3_HJM_2F_procedure_1_poly_model_simulated_10Y_mean")
```


```{r}
# zero_coupon_yields_phase_3_HJM_2F_spline_model_simulated_10Y_mean <- simulate_n_m_hjm_fun(zero_coupon_yields_phase_3_HJM_2F_procedure_1_spline_model, n = 252 * 10, m = 1, only_mean = T, show_time = T)
# write_parquet(as.data.frame(zero_coupon_yields_phase_3_HJM_2F_spline_model_simulated_10Y_mean), "Simulated Data/zero_coupon_yields_phase_3_HJM_2F_spline_model_simulated_10Y_mean")
# 
# zero_coupon_yields_phase_3_HJM_2F_procedure_1_spline_model_simulated_10Y_mean <- simulate_n_m_hjm_fun(zero_coupon_yields_phase_3_HJM_2F_procedure_1_spline_model, n = 252 * 10, m = 1, extrapolate = T, only_mean = T, show_time = T)
# write_parquet(as.data.frame(zero_coupon_yields_phase_3_HJM_2F_procedure_1_spline_model_simulated_10Y_mean), "Simulated Data/zero_coupon_yields_phase_3_HJM_2F_procedure_1_spline_model_simulated_10Y_mean")
```

```{r}
# zero_coupon_yields_phase_3_HJM_2F_procedure_2_poly_model_simulated_10Y_mean <- simulate_n_m_hjm_fun(zero_coupon_yields_phase_3_HJM_2F_procedure_2_poly_model, n = 252 * 10, m = 1, only_mean = T, show_time = T)
# write_parquet(as.data.frame(zero_coupon_yields_phase_3_HJM_2F_procedure_2_poly_model_simulated_10Y_mean), "Simulated Data/zero_coupon_yields_phase_3_HJM_2F_procedure_2_poly_model_simulated_10Y_mean")
```

```{r}
# zero_coupon_yields_phase_3_HJM_2F_procedure_2_spline_model_simulated_10Y_mean <- simulate_n_m_hjm_fun(zero_coupon_yields_phase_3_HJM_2F_procedure_2_spline_model, n = 252 * 10, m = 1, only_mean = T, show_time = T)
# write_parquet(as.data.frame(zero_coupon_yields_phase_3_HJM_2F_procedure_2_spline_model_simulated_10Y_mean), "Simulated Data/zero_coupon_yields_phase_3_HJM_2F_procedure_2_spline_model_simulated_10Y_mean")
```

# Plotting Simulated HJM Model

```{r}
plot_simulated_rates_fun <- function(rates, plot_title = "blank", rate = NULL, type = NULL, name = NULL, plot_size = c(10, 5)) {
  if (!is.null(rate)) {
    rates <- rates[, c("realization", "time", rate)]
  }
  m <- n_distinct(rates[,"realization"])
  n <- n_distinct(rates[,"time"]) - 1
  
  rates[,"time"] <- rep(0:n, m)
  
  rates_df <- as.data.frame(rates)
  rates_df$realization <- as.factor(rates_df$realization)
  rates_df$time <- as.integer(rates_df$time)
  
  tenors <- as.numeric(colnames(rates))[-c(1,2)]
  tenor_lim <- c(0, ceiling(max(tenors)))
  
  rates_df_compact <- reshape2::melt(rates_df, id.vars = c("realization", "time"), variable.name = "tenor", value.name = "forward_rate")
  
  if (is.null(rate)) {
    rates_df_compact$tenor <- as.numeric(levels(rates_df_compact$tenor))[rates_df_compact$tenor]
    color_manual <- custom_viridis(10)
  } else {
    color_manual <- scale_colour_viridis_d("Tenor (Years)")
  }
  
  forward_rate_time_plot <- ggplot(rates_df_compact) +
    geom_line(aes(x = time, y = forward_rate * 100, group = interaction(tenor, realization), color = tenor), size = .4) +
    # labs(title = plot_title, x = "Time", y = "Rate") +
    labs(x = "Time", y = "Rate") +
    scale_y_continuous(labels = scales::percent_format(scale = 1)) +
    color_manual +
    custom_theme()
  
  print(forward_rate_time_plot)

  if (!is.null(name)) {
    ggsave(paste0(name, "_time_plot.png"), forward_rate_time_plot, "png", paste0("Figs/Simulated ", type), width = plot_size[1], height = plot_size[2])
  }
}

plot_simulated_rates_prediction_intervals_fun <- function(rates, plot_title, rate = NULL, type = NULL, name = NULL, plot_size = c(10, 5)) {
  if (!is.null(rate)) {
    rates <- rates[, c("realization", "time", rate)]
  }
  
  m <- n_distinct(rates[,"realization"])
  n <- n_distinct(rates[,"time"]) - 1
  
  rates[,"time"] <- rep(0:n, m)
  
  rates_df <- as.data.frame(rates)
  rates_df$realization <- as.factor(rates_df$realization)
  rates_df$time <- as.integer(rates_df$time)
  
  tenors <- as.numeric(colnames(rates))[-c(1,2)]
  tenor_lim <- c(0, ceiling(max(tenors)))
  
  rates_df_compact <- reshape2::melt(rates_df, id.vars = c("realization", "time"), variable.name = "tenor", value.name = "rate")
  
  if (is.null(rate)) {
    rates_df_compact$tenor <- as.numeric(levels(rates_df_compact$tenor))[rates_df_compact$tenor]
    color_manual <- custom_viridis(10)
    fill_manual <- scale_fill_viridis_c(n.breaks = 10, guide = "none")
  } else {
    color_manual <- scale_colour_viridis_d("Tenor (Years)")
    fill_manual <- scale_fill_viridis_d(guide = "none")
  }
  
  rates_quantiles_df <- rates_df_compact %>%
    group_by(time, tenor) %>%
    summarize(lower = quantile(rate, 0.05), upper = quantile(rate, 0.95), mean = mean(rate))
  
  # rates_quantiles_df$tenor <- as.factor(rates_quantiles_df$tenor)
  
  rates_quantiles_plot <- ggplot(rates_quantiles_df) +
    geom_line(aes(x = time, y = mean * 100, group = tenor, color = tenor), size = 1) +
    geom_ribbon(aes(x = time, ymin = lower * 100, ymax = upper * 100, group = tenor, fill = tenor), alpha = 0.5) +
    # labs(title = plot_title, x = "Time", y = "Rate") +
    labs(x = "Time", y = "Rate") +
    scale_y_continuous(labels = scales::percent_format(scale = 1)) +
    color_manual +
    fill_manual +
    custom_theme()
  
  print(rates_quantiles_plot)
  
  if (!is.null(name)) {
    ggsave(paste0(name, "_quantiles_plot.png"), rates_quantiles_plot, "png", paste0("Figs/Simulated ", type), width = plot_size[1], height = plot_size[2])
  }
}

plot_all_rates_fun <- function(rates, simulated_rates, plot_title = "Rates", rate = NULL, type = NULL, name = NULL, plot_size = c(10, 5)) {
  time <- seq_len(nrow(rates))
  rates <- cbind(time, rates)
  rates_df <- as.data.frame(rates)
  rates_df$time <- as.integer(rates_df$time)
  
  m <- n_distinct(simulated_rates[,"realization"])
  n <- n_distinct(simulated_rates[,"time"]) - 1
  simulated_rates[,"time"] <- rep(max(time):(max(time) + n), m)
  
  simulated_rates_df <- as.data.frame(simulated_rates)
  simulated_rates_df$realization <- as.factor(simulated_rates_df$realization)
  simulated_rates_df$time <- as.integer(simulated_rates_df$time)
  
  tenors <- as.numeric(colnames(rates))[-1]
  tenor_lim <- c(0, ceiling(max(tenors)))
  
  if (!is.null(rate)) {
    rates_df <- rates_df[, c("time", rate)]
    simulated_rates_df <- simulated_rates_df[, c("realization", "time", rate)]
  }
  
  rates_df_compact <- reshape2::melt(rates_df, id.vars = "time", variable.name = "tenor", value.name = "rate")
  rates_df_compact$tenor <- as.numeric(levels(rates_df_compact$tenor))[rates_df_compact$tenor]
  
  simulated_rates_df_compact <- reshape2::melt(simulated_rates_df, id.vars = c("realization", "time"), variable.name = "tenor", value.name = "rate")
  simulated_rates_df_compact$tenor <- as.numeric(levels(simulated_rates_df_compact$tenor))[simulated_rates_df_compact$tenor]
  
  if (is.null(rate)) {
    color_manual <- custom_viridis(10)
    fill_manual <- scale_fill_viridis_c(n.breaks = 10, guide = "none")
  } else {
    color_manual <- scale_colour_viridis_d("Tenor (Years)")
    fill_manual <- scale_fill_viridis_d(guide = "none")
  }
  
  rates_time_plot <- ggplot(rates_df_compact) +
    geom_line(aes(x = time, y = rate * 100, group = tenor, color = tenor), size = .4) +
    geom_line(aes(x = time, y = rate * 100, group = interaction(tenor, realization), color = tenor), simulated_rates_df_compact, linetype = 2, size = .4) +
    # labs(title = plot_title, x = "Time", y = "Rate") +
    labs(x = "Time", y = "Rate") +
    scale_y_continuous(labels = scales::percent_format(scale = 1)) +
    color_manual +
    fill_manual +
    custom_theme()
  
  print(rates_time_plot)
  
  if (!is.null(name)) {
    ggsave(paste0(name, "_time_all_plot.png"), rates_time_plot, "png", paste0("Figs/Simulated ", type), width = plot_size[1], height = plot_size[2])
  }
}
```

```{r}
plot_simulated_rates_fun(zero_coupon_yields_phase_3_HJM_2F_poly_model_simulated_10Y_mean, "Zero Coupon Phase 3 Simulated Yields 2F Model", type = "Interest Rates", name = "zero_coupon_yields_phase_3_HJM_2F_poly_model_simulated_10Y_mean")
plot_simulated_rates_fun(zero_coupon_yields_phase_3_HJM_2F_poly_model_simulated_10Y_mean, "Zero Coupon Phase 3 Simulated Yields 2F Model", type = "Interest Rates", name = "zero_coupon_yields_phase_3_HJM_2F_poly_model_simulated_10Y_mean_small", plot_size = c(10, 4))
plot_simulated_rates_fun(zero_coupon_yields_phase_3_HJM_2F_procedure_1_poly_model_simulated_10Y_mean, "Zero Coupon Phase 3 Simulated Yields 2F Model", type = "Interest Rates", name = "zero_coupon_yields_phase_3_HJM_2F_procedure_1_poly_model_simulated_10Y_mean")
plot_simulated_rates_fun(zero_coupon_yields_phase_3_HJM_2F_procedure_1_poly_model_simulated_10Y_mean, "Zero Coupon Phase 3 Simulated Yields 2F Model", type = "Interest Rates", name = "zero_coupon_yields_phase_3_HJM_2F_procedure_1_poly_model_simulated_10Y_mean_small", plot_size = c(10, 4))
plot_simulated_rates_fun(zero_coupon_yields_phase_3_HJM_2F_procedure_2_poly_model_simulated_10Y_mean, "Zero Coupon Phase 3 Simulated Yields 2F Model", type = "Interest Rates", name = "zero_coupon_yields_phase_3_HJM_2F_procedure_2_poly_model_simulated_10Y_mean")
plot_simulated_rates_fun(zero_coupon_yields_phase_3_HJM_2F_procedure_2_poly_model_simulated_10Y_mean, "Zero Coupon Phase 3 Simulated Yields 2F Model", type = "Interest Rates", name = "zero_coupon_yields_phase_3_HJM_2F_procedure_2_poly_model_simulated_10Y_mean_small", plot_size = c(10, 4))

plot_simulated_rates_fun(zero_coupon_yields_phase_3_HJM_2F_spline_model_simulated_10Y_mean, "Zero Coupon Phase 3 Simulated Yields 2F Model", type = "Interest Rates", name = "zero_coupon_yields_phase_3_HJM_2F_spline_model_simulated_10Y_mean")
plot_simulated_rates_fun(zero_coupon_yields_phase_3_HJM_2F_spline_model_simulated_10Y_mean, "Zero Coupon Phase 3 Simulated Yields 2F Model", type = "Interest Rates", name = "zero_coupon_yields_phase_3_HJM_2F_spline_model_simulated_10Y_mean_small", plot_size = c(10, 4))
plot_simulated_rates_fun(zero_coupon_yields_phase_3_HJM_2F_procedure_1_spline_model_simulated_10Y_mean, "Zero Coupon Phase 3 Simulated Yields 2F Model", type = "Interest Rates", name = "zero_coupon_yields_phase_3_HJM_2F_procedure_1_spline_model_simulated_10Y_mean")
plot_simulated_rates_fun(zero_coupon_yields_phase_3_HJM_2F_procedure_1_spline_model_simulated_10Y_mean, "Zero Coupon Phase 3 Simulated Yields 2F Model", type = "Interest Rates", name = "zero_coupon_yields_phase_3_HJM_2F_procedure_1_spline_model_simulated_10Y_mean_small", plot_size = c(10, 4))
plot_simulated_rates_fun(zero_coupon_yields_phase_3_HJM_2F_procedure_2_spline_model_simulated_10Y_mean, "Zero Coupon Phase 3 Simulated Yields 2F Model", type = "Interest Rates", name = "zero_coupon_yields_phase_3_HJM_2F_procedure_2_spline_model_simulated_10Y_mean")
plot_simulated_rates_fun(zero_coupon_yields_phase_3_HJM_2F_procedure_2_spline_model_simulated_10Y_mean, "Zero Coupon Phase 3 Simulated Yields 2F Model", type = "Interest Rates", name = "zero_coupon_yields_phase_3_HJM_2F_procedure_2_spline_model_simulated_10Y_mean_small", plot_size = c(10, 4))
```

```{r}
plot_all_rates_fun(zero_coupon_yields_phase_3, zero_coupon_yields_phase_3_HJM_2F_poly_model_simulated_10Y_mean, "Zero Coupon Phase 3 Simulated Yields 2F Model", type = "Interest Rates", name = "zero_coupon_yields_phase_3_HJM_2F_poly_model_simulated_10Y_mean")
plot_all_rates_fun(zero_coupon_yields, zero_coupon_yields_phase_3_HJM_2F_poly_model_simulated_10Y_mean, "Zero Coupon Simulated Yields 2F Model", type = "Interest Rates", name = "zero_coupon_yields_HJM_2F_poly_model_simulated_10Y_mean")

plot_all_rates_fun(zero_coupon_yields_extrapolated_3M_phase_3, zero_coupon_yields_phase_3_HJM_2F_procedure_1_poly_model_simulated_10Y_mean, "Zero Coupon Phase 3 Simulated Yields 2F Model", type = "Interest Rates", name = "zero_coupon_yields_phase_3_HJM_2F_procedure_1_poly_model_simulated_10Y_mean")
plot_all_rates_fun(zero_coupon_yields_extrapolated_3M, zero_coupon_yields_phase_3_HJM_2F_procedure_1_poly_model_simulated_10Y_mean, "Zero Coupon Simulated Yields 2F Model", type = "Interest Rates", name = "zero_coupon_yields_HJM_2F_procedure_1_poly_model_simulated_10Y_mean")

plot_all_rates_fun(zero_coupon_yields_extrapolated_3M_phase_3, zero_coupon_yields_phase_3_HJM_2F_procedure_2_poly_model_simulated_10Y_mean, "Zero Coupon Phase 3 Simulated Yields 2F Model", type = "Interest Rates", name = "zero_coupon_yields_phase_3_HJM_2F_procedure_2_poly_model_simulated_10Y_mean")
plot_all_rates_fun(zero_coupon_yields_extrapolated_3M, zero_coupon_yields_phase_3_HJM_2F_procedure_2_poly_model_simulated_10Y_mean, "Zero Coupon Simulated Yields 2F Model", type = "Interest Rates", name = "zero_coupon_yields_HJM_2F_procedure_2_poly_model_simulated_10Y_mean")

plot_all_rates_fun(zero_coupon_yields_phase_3, zero_coupon_yields_phase_3_HJM_2F_spline_model_simulated_10Y_mean, "Zero Coupon Phase 3 Simulated Yields 2F Model", type = "Interest Rates", name = "zero_coupon_yields_phase_3_HJM_2F_spline_model_simulated_10Y_mean")
plot_all_rates_fun(zero_coupon_yields, zero_coupon_yields_phase_3_HJM_2F_spline_model_simulated_10Y_mean, "Zero Coupon Simulated Yields 2F Model", type = "Interest Rates", name = "zero_coupon_yields_HJM_2F_spline_model_simulated_10Y_mean")

plot_all_rates_fun(zero_coupon_yields_extrapolated_3M_phase_3, zero_coupon_yields_phase_3_HJM_2F_procedure_1_spline_model_simulated_10Y_mean, "Zero Coupon Phase 3 Simulated Yields 2F Model", type = "Interest Rates", name = "zero_coupon_yields_phase_3_HJM_2F_procedure_1_spline_model_simulated_10Y_mean")
plot_all_rates_fun(zero_coupon_yields_extrapolated_3M, zero_coupon_yields_phase_3_HJM_2F_procedure_1_spline_model_simulated_10Y_mean, "Zero Coupon Simulated Yields 2F Model", type = "Interest Rates", name = "zero_coupon_yields_HJM_2F_procedure_1_spline_model_simulated_10Y_mean")

plot_all_rates_fun(zero_coupon_yields_extrapolated_3M_phase_3, zero_coupon_yields_phase_3_HJM_2F_procedure_2_spline_model_simulated_10Y_mean, "Zero Coupon Phase 3 Simulated Yields 2F Model", type = "Interest Rates", name = "zero_coupon_yields_phase_3_HJM_2F_procedure_2_spline_model_simulated_10Y_mean")
plot_all_rates_fun(zero_coupon_yields_extrapolated_3M, zero_coupon_yields_phase_3_HJM_2F_procedure_2_spline_model_simulated_10Y_mean, "Zero Coupon Simulated Yields 2F Model", type = "Interest Rates", name = "zero_coupon_yields_HJM_2F_procedure_2_spline_model_simulated_10Y_mean")
```

# Leave-group-out Cross Validation

```{r}
MSPE_fun <- function(rates_test, rates_simulated) {
  if (!is.matrix(rates_test)) {
    MSPE <- (rates_test - rates_simulated)^2
  } else {
    MSPE <- apply((rates_test - rates_simulated)^2, 2, mean)
  }
  return(MSPE)
}

RMSPE_fun <- function(rates_test, rates_simulated) {
  if (!is.matrix(rates_test)) {
    RMSPE <- sqrt((rates_test - rates_simulated)^2)
  } else {
    RMSPE <- sqrt(apply((rates_test - rates_simulated)^2, 2, mean))
  }
  return(RMSPE)
}

MAPE_fun <- function(rates_test, rates_simulated) {
  if (!is.matrix(rates_test)) {
    MAPE <- abs(rates_test - rates_simulated)
  } else {
    MAPE <- apply(abs(rates_test - rates_simulated), 2, mean)
  }
  return(MAPE)
}
```

```{r}
LGOCV_fun <- function(rates, procedure, volatility_fit_method, pca_tolerance = 0.99, n_shift = 252*5, n_predict = 252, extrapolate_method = "Nelson Siegel", frequency = 1/12, n_components = NULL, only_mean = T) {
  rates_extrapolated <- rates
  
  if (procedure == "1" | procedure == "2") {
    rates_extrapolated <- extrapolate_fun(rates, frequency, extrapolate_method)
  }
  
  all_train_rates <- rates[1:(nrow(rates) - n_predict + 1),]
  
  results <- future_lapply(seq_len(n_shift), function(i) {
    train_rates <- all_train_rates[1:(nrow(all_train_rates) - i),]
    test_rates <- rates_extrapolated[(nrow(train_rates) + 1):(nrow(train_rates) + n_predict),]
    
    fitted_model <- fit_HJM_fun(train_rates, procedure = procedure, pca_tolerance = pca_tolerance, extrapolate_frequency = frequency, n_components = n_components, volatility_fit_method = volatility_fit_method)
    simulated_rates <- simulate_n_hjm_fun(fitted_model, n_predict, only_mean)[,-1]
    
    if (procedure == "1") {
      simulated_rates <- extrapolate_fun(simulated_rates, frequency)[-1,]
    } else {
      simulated_rates <- simulated_rates[-1,]
    }
    
    loss_values <- list(RMSPE = RMSPE_fun(test_rates, simulated_rates),
                        # MSPE = MSPE_fun(test_rates, simulated_rates),
                        MAPE = MAPE_fun(test_rates, simulated_rates))
    
    return(loss_values)
  }, future.seed = 1234)
  
  loss_values <- list(RMSPE = do.call(rbind, lapply(results, function(x) x$RMSPE)),
                      # MSPE = do.call(rbind, lapply(results, function(x) x$MSPE)),
                      MAPE = do.call(rbind, lapply(results, function(x) x$MAPE)))
  
  loss_values_average <- list(RMSPE = colMeans(loss_values$RMSPE),
                              # MSPE = colMeans(loss_values$MSPE),
                              MAPE = colMeans(loss_values$MAPE))
  
  return(list(model = paste0("P: ", procedure, "\nV: ", volatility_fit_method, "\n"), loss_values_average = loss_values_average, loss_values = loss_values, procedure = procedure, volatility_fit_method = volatility_fit_method))
}
```

```{r}
zero_coupon_yields_phase_3_HJM_2F_procedure_1_poly_model_LGOCV <- LGOCV_fun(zero_coupon_yields_phase_3, "1", "linear", n_shift = 100, n_predict = 100, n_components = 2)
zero_coupon_yields_phase_3_HJM_2F_procedure_1_spline_model_LGOCV <- LGOCV_fun(zero_coupon_yields_phase_3, "1", "spline", n_shift = 100, n_predict = 100, n_components = 2)
zero_coupon_yields_phase_3_HJM_2F_procedure_2_poly_model_LGOCV <- LGOCV_fun(zero_coupon_yields_phase_3, "2", "linear", n_shift = 100, n_predict = 100, n_components = 2)
zero_coupon_yields_phase_3_HJM_2F_procedure_2_spline_model_LGOCV <- LGOCV_fun(zero_coupon_yields_phase_3, "2", "spline", n_shift = 100, n_predict = 100, n_components = 2)
```

```{r}
plot_all_error_fun <- function(LGOCVs, plot_title, name = NULL, plot_size = c(10, 5)) {
  all_errors <- as.data.frame(t(do.call(cbind, lapply(LGOCVs, function(x) do.call(cbind, x$loss_values_average)))))
  all_errors$Measure <- rownames(as.data.frame(t(do.call(cbind, LGOCVs[[1]]$loss_values_average))))
  methods <- rev(rep(do.call(c, lapply(LGOCVs, function(x) x$model)), each = length(unique(all_errors$Measure))))
  plot_order <- rev(rep(seq_along(LGOCVs), each = length(unique(all_errors$Measure))))
  all_errors$plot_order <- as.factor(plot_order)
  
  all_errors_compact <- reshape2::melt(all_errors, id.vars = c("Measure", "plot_order"), variable.name = "tenor", value.name = "error")
  all_errors_compact$tenor <- as.numeric(levels(all_errors_compact$tenor))[all_errors_compact$tenor]
  all_errors_compact$Measure <- as.factor(all_errors_compact$Measure)
  
  error_plot <- ggplot(all_errors_compact) +
    geom_line(aes(x = tenor, y = error, color = plot_order, linewidth = plot_order, linetype = Measure), size = 1.25) +
    # labs(title = plot_title, x = "Tenor", y = "Error") +
    labs(x = "Tenor", y = "Value") +
    # scale_color_viridis_d() +
    custom_theme() +
    scale_linewidth_manual(values = seq(length(LGOCVs), by = -1, length.out = length(LGOCVs)), guide = "none") +
    scale_color_viridis_d(name = "Model:", labels = unique(methods), guide = guide_legend(reverse = TRUE)) +
    theme(legend.position = "none")
  
  print(error_plot)
  
  if (!is.null(name)) {
    ggsave(paste0(name, "_error_plot.png"), error_plot, "png", "Figs/Error", width = plot_size[1], height = plot_size[2])
  }
}
```

```{r}
plot_all_error_fun(list(zero_coupon_yields_phase_3_HJM_2F_procedure_1_poly_model_LGOCV, zero_coupon_yields_phase_3_HJM_2F_procedure_1_spline_model_LGOCV, zero_coupon_yields_phase_3_HJM_2F_procedure_2_poly_model_LGOCV, zero_coupon_yields_phase_3_HJM_2F_procedure_2_spline_model_LGOCV), "Zero Coupon Phase 3 LGOCV Error", name = "zero_coupon_yields_phase_3_HJM_2F_LGOCV")
plot_all_error_fun(list(zero_coupon_yields_phase_3_HJM_2F_procedure_1_poly_model_LGOCV, zero_coupon_yields_phase_3_HJM_2F_procedure_1_spline_model_LGOCV, zero_coupon_yields_phase_3_HJM_2F_procedure_2_poly_model_LGOCV, zero_coupon_yields_phase_3_HJM_2F_procedure_2_spline_model_LGOCV), "Zero Coupon Phase 3 LGOCV Error", name = "zero_coupon_yields_phase_3_HJM_2F_LGOCV_small", plot_size = c(10, 4))
```
